import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/shared/NavBar/NavBar";
import TopNav from "@/components/shared/TopNav/TopNav";
// import { initFlowbite } from "flowbite";

// const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="">
      <head>
      </head>
      <body
        // className={inter.className}
        className="font-kumbh dark:bg-gray-800"
      >
        <TopNav></TopNav>
        <NavBar></NavBar>
        {children}
      </body>
    </html>
  );
}
