import type { Metadata } from "next";
// import { Inter } from "next/font/google";
import { kumbh, jost } from "./fonts";
import "./globals.css";
import NavBar from "@/components/shared/NavBar/NavBar";
import TopNav from "@/components/shared/TopNav/TopNav";
// import { initFlowbite } from "flowbite";


export const metadata: Metadata = {
  title: "Style Mela",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en"
      className={`${kumbh.variable} ${jost.variable}`}
    >
      <head>
      </head>
      <body
        // className={inter.className}
        className="font-kumbh dark:bg-gray-800"
      >
        <TopNav></TopNav>
        <NavBar></NavBar>
        {children}
      </body>
    </html>
  );
}
